version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: factureTrigger
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d factureTrigger"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: