spring.application.name=FactureTrigger
server.port=8083

app.cors.allowed-origin=http://localhost:4200

spring.datasource.url=jdbc:postgresql://localhost:5432/factureTrigger
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:init-db/01-schema.sql
spring.jpa.defer-datasource-initialization=true

jwt.secret=mysupersecretkeymylongchainsecretkey123452026
jwt.expiration=3600000